# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/biog/Documents/Projects/Uni/SystemSoftware_MemoryManagement

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/biog/Documents/Projects/Uni/SystemSoftware_MemoryManagement

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/biog/Documents/Projects/Uni/SystemSoftware_MemoryManagement/CMakeFiles /home/biog/Documents/Projects/Uni/SystemSoftware_MemoryManagement//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/biog/Documents/Projects/Uni/SystemSoftware_MemoryManagement/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SystemSoftware_MemoryManagement

# Build rule for target.
SystemSoftware_MemoryManagement: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SystemSoftware_MemoryManagement
.PHONY : SystemSoftware_MemoryManagement

# fast build rule for target.
SystemSoftware_MemoryManagement/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/build
.PHONY : SystemSoftware_MemoryManagement/fast

src/Block.o: src/Block.cpp.o
.PHONY : src/Block.o

# target to build an object file
src/Block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/src/Block.cpp.o
.PHONY : src/Block.cpp.o

src/Block.i: src/Block.cpp.i
.PHONY : src/Block.i

# target to preprocess a source file
src/Block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/src/Block.cpp.i
.PHONY : src/Block.cpp.i

src/Block.s: src/Block.cpp.s
.PHONY : src/Block.s

# target to generate assembly for a file
src/Block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/src/Block.cpp.s
.PHONY : src/Block.cpp.s

src/Heap.o: src/Heap.cpp.o
.PHONY : src/Heap.o

# target to build an object file
src/Heap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/src/Heap.cpp.o
.PHONY : src/Heap.cpp.o

src/Heap.i: src/Heap.cpp.i
.PHONY : src/Heap.i

# target to preprocess a source file
src/Heap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/src/Heap.cpp.i
.PHONY : src/Heap.cpp.i

src/Heap.s: src/Heap.cpp.s
.PHONY : src/Heap.s

# target to generate assembly for a file
src/Heap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/src/Heap.cpp.s
.PHONY : src/Heap.cpp.s

src/TypeDescriptor.o: src/TypeDescriptor.cpp.o
.PHONY : src/TypeDescriptor.o

# target to build an object file
src/TypeDescriptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/src/TypeDescriptor.cpp.o
.PHONY : src/TypeDescriptor.cpp.o

src/TypeDescriptor.i: src/TypeDescriptor.cpp.i
.PHONY : src/TypeDescriptor.i

# target to preprocess a source file
src/TypeDescriptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/src/TypeDescriptor.cpp.i
.PHONY : src/TypeDescriptor.cpp.i

src/TypeDescriptor.s: src/TypeDescriptor.cpp.s
.PHONY : src/TypeDescriptor.s

# target to generate assembly for a file
src/TypeDescriptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/src/TypeDescriptor.cpp.s
.PHONY : src/TypeDescriptor.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemSoftware_MemoryManagement.dir/build.make CMakeFiles/SystemSoftware_MemoryManagement.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SystemSoftware_MemoryManagement"
	@echo "... src/Block.o"
	@echo "... src/Block.i"
	@echo "... src/Block.s"
	@echo "... src/Heap.o"
	@echo "... src/Heap.i"
	@echo "... src/Heap.s"
	@echo "... src/TypeDescriptor.o"
	@echo "... src/TypeDescriptor.i"
	@echo "... src/TypeDescriptor.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

